[profile.default]
src = "src"
out = "out"
libs = ["lib"]
ignored_warnings_from = [
    "lib/openzeppelin-contracts/contracts/proxy/Proxy.sol"
]
bytecode_hash = "none"
optimizer = true
optimizer_runs = 200

